name: fsdl-3d-recon
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7  # versioned to match Google Colab  # version also pinned in Dockerfile
  - pip=21.1.3  # versioned to match Google Colab  # version also pinned in Dockerfile
