version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: model/Dockerfile
  frontend:
    environment:
      - LAMBDA_FUNCTION_URL
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    ports:
      - "5000:5000"
